wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.12
    start_time: 1647516307
    t:
      1:
      - 1
      - 41
      3:
      - 16
      4: 3.8.12
      5: 0.12.11
      8:
      - 2
      - 5
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 100
