epochs:
  desc: Number of epochs to train over
  value: 1
batch_size:
  desc: Size of each mini-batch
  value: 10
train_fn:
  value: train
noise_multiplier:
 value: 0.1
max_grad_norm:
  value: 1.1
target_delta:
  value: 1e-4
strategy:
  value: DP_Fed


